SET CPU_TYPE=SSE-300-MPS3
SET CPU_VENDOR=ARM
SET UV2_TARGET=Cortex-M55_MPS3
SET CPU_CLOCK=0x01F78A40
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\platform.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\serial.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\perf_counter.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\startup_fvp_sse300_mps3.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\system_sse300mps3.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\core_list_join.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\core_main.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\core_matrix.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\core_state.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\core_util.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\core_portme.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\objects\eventrecorder.__i"
"C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc" @".\Objects\GCC_TE~1.LNP"
arm-none-eabi-size.exe ./Objects/gcc_template.elf
